### ISSUE TITLE
Issues with airtouch5 connected to two units

### ISSUE THREAD

**Issue by mcmike313** [cemilbrowne/homebridge-airtouch5-platform#7]
**Describe Your Problem:**
1 airtouch5 with two units connected results in the following error

**Logs:**
(AirTouch5) is running on port 48745. TypeError: Cannot read properties of undefined (reading 'zone_name')     at Airtouch5Wrapper.AddZoneName (/usr/local/lib/node_modules/homebridge-airtouch5-platform/src/airTouchWrapper.ts:102:32)     at AirtouchPlatform.onZoneNameNotification (/usr/local/lib/node_modules/homebridge-airtouch5-platform/src/platform.ts:141:14)     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/homebridge-airtouch5-platform/src/platform.ts:79:12)     at EventEmitter.emit (node:events:514:28)
```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

{
    "name": "AirTouch5",
    "platform": "Airtouch5",
    "units": [
        "192.168.1.211"
    ],
    "_bridge": {
        "username": "**********",
        "port": 48745
    }
}

**Screenshots:**
![image](https://github.com/cemilbrowne/homebridge-airtouch5-platform/assets/20370045/47c53c80-b2f9-4ef9-ad6a-9bef0c01622e)
![image](https://github.com/cemilbrowne/homebridge-airtouch5-platform/assets/20370045/78ed7e4f-1edb-47a6-aa61-a70fdaf73350)
![image](https://github.com/cemilbrowne/homebridge-airtouch5-platform/assets/20370045/cefce714-28a8-4b70-89da-b1bb073bcc0a)
![image](https://github.com/cemilbrowne/homebridge-airtouch5-platform/assets/20370045/332986b3-ae96-4b52-8a90-87c15cda0396)

**Environment:**

* **Plugin Version**: Homebridge v1.7.0 (HAP v0.11.1)  homebridge-airtouch5-platform v1.7.0
* **Operating System**: macOS

**Comment by mcmike313** [comment]
think the issue lies in how it is reading the zones if its a nested list of somekind, are you able to assist?

**Comment by cemilbrowne** [comment]
Hi Mike; 

I'll probably need some more details - could you turn on debug logging for me so I can see what's going on?  It's hard for me to be able to tell what's going on, but you're almost certainly right about the nested list.

**Comment by mcmike313** [comment]
`[2/15/2024, 12:05:14 PM] [AirTouch5] API     | Connected to Airtouch
[2/15/2024, 12:05:14 PM] [AirTouch5] API     | Assembling extended message to get information
[2/15/2024, 12:05:14 PM] [AirTouch5] API     | Got Extended message - AC ABILITY
[2/15/2024, 12:05:14 PM] [AirTouch5] ATWRAP  | Creating AC: 0{"ac_unit_number":0,"ac_name":"Daikin 12.5","ac_start_zone":0,"ac_zone_count":4,"ac_support_cool_mode":1,"ac_support_fan_mode":1,"ac_support_dry_mode":1,"ac_support_heat_mode":1,"ac_support_auto_mode":1,"ac_support_fan_intelligent":0,"ac_support_fan_turbo":0,"ac_support_fan_powerful":0,"ac_support_fan_high":1,"ac_support_fan_medium":1,"ac_support_fan_low":1,"ac_support_fan_quiet":0,"ac_support_fan_auto":0,"ac_min_cool":16,"ac_max_cool":32,"ac_min_heat":16,"ac_max_heat":32}
[2/15/2024, 12:05:14 PM] [AirTouch5] ATWRAP  | Creating Zone: 
[2/15/2024, 12:05:14 PM] [AirTouch5] ATWRAP  | Creating Zone: 
[2/15/2024, 12:05:14 PM] [AirTouch5] ATWRAP  | Creating Zone: 
[2/15/2024, 12:05:14 PM] [AirTouch5] ATWRAP  | Creating Zone: 
[2/15/2024, 12:05:14 PM] [AirTouch5] API     | Assembling standard message with type 23
[2/15/2024, 12:05:14 PM] [AirTouch5] API     | Assembling standard message with type 21
[2/15/2024, 12:05:14 PM] [AirTouch5] ATWRAP  | Updating AC status: {"ac_unit_number":0,"ac_power_state":0,"ac_mode":4,"ac_fan_speed":2,"ac_target":22,"ac_temp":20,"ac_spill":0,"ac_timer":1,"ac_error_code":0}
[2/15/2024, 12:05:14 PM] [AirTouch5] ATWRAP  | Register AC being called for acnumber: 0
[2/15/2024, 12:05:14 PM] [AirTouch5] ATWRAP  | Updating AC status: {"ac_unit_number":0,"ac_power_state":8,"ac_mode":0,"ac_fan_speed":0,"ac_target":10.1,"ac_temp":3041.3,"ac_spill":1,"ac_timer":0,"ac_error_code":700}
[2/15/2024, 12:05:14 PM] [AirTouch5] ATWRAP  | Updating Zone status: {"zone_number":0,"zone_power_state":1,"zone_control_type":1,"zone_damper_position":15,"zone_target":22,"zone_temp":20.4,"zone_battery_low":0,"zone_has_sensor":1,"zone_has_spill":0}
[2/15/2024, 12:05:14 PM] [AirTouch5] ATWRAP  | Updating Zone status: {"zone_number":1,"zone_power_state":1,"zone_control_type":1,"zone_damper_position":0,"zone_target":22,"zone_temp":20.7,"zone_battery_low":0,"zone_has_sensor":1,"zone_has_spill":0}
[2/15/2024, 12:05:14 PM] [AirTouch5] ATWRAP  | Updating Zone status: {"zone_number":2,"zone_power_state":1,"zone_control_type":1,"zone_damper_position":0,"zone_target":23,"zone_temp":20.7,"zone_battery_low":0,"zone_has_sensor":1,"zone_has_spill":0}
[2/15/2024, 12:05:14 PM] [AirTouch5] ATWRAP  | Updating Zone status: {"zone_number":3,"zone_power_state":1,"zone_control_type":1,"zone_damper_position":0,"zone_target":22,"zone_temp":20.4,"zone_battery_low":0,"zone_has_sensor":1,"zone_has_spill":0}
[2/15/2024, 12:05:14 PM] [AirTouch5] ATWRAP  | Updating Zone status: {"zone_number":4,"zone_power_state":1,"zone_control_type":1,"zone_damper_position":0,"zone_target":22,"zone_temp":20.4,"zone_battery_low":0,"zone_has_sensor":1,"zone_has_spill":0}
[2/15/2024, 12:05:14 PM] [AirTouch5] ATWRAP  | Got an updated zone status, but zone hasn't been initialised yet number: 4
[2/15/2024, 12:05:14 PM] [AirTouch5] ATWRAP  | Updating Zone status: {"zone_number":5,"zone_power_state":1,"zone_control_type":1,"zone_damper_position":0,"zone_target":22,"zone_temp":20.8,"zone_battery_low":0,"zone_has_sensor":1,"zone_has_spill":0}
[2/15/2024, 12:05:14 PM] [AirTouch5] ATWRAP  | Got an updated zone status, but zone hasn't been initialised yet number: 5
[2/15/2024, 12:05:14 PM] [AirTouch5] API     | Assembling extended message to get information
[2/15/2024, 12:05:14 PM] [AirTouch5] API     | Got Extended message - ZONE NAMES
[2/15/2024, 12:05:14 PM] [AirTouch5] Child bridge process ended
[2/15/2024, 12:05:14 PM] [AirTouch5] Process Ended. Code: 1, Signal: null
[2/15/2024, 12:05:21 PM] [AirTouch5] Restarting Process...`

**Comment by captaincafeman** [comment]
I have exactly the same issue - any updates on this?

**Comment by cemilbrowne** [comment]
OK team; let me see what I can do here - sorry I've been a bit distracted.

**Comment by cemilbrowne** [comment]
Hi @captaincafeman  and @mcmike313 - I _think_ I've fixed this error - can you test with latest and give me some debugging please?

**Comment by cemilbrowne** [comment]
@captaincafeman can you turn on debug logging for me and restart, and capture?  THanks.

**Comment by captaincafeman** [comment]
Detailed logs below - the second zone is called "Parents", I believe it's the slaved zone.

-----

[6/11/2025, 10:11:20 AM] [Airtouch 5] Initializing Airtouch5 platform...
[6/11/2025, 10:11:20 AM] [Airtouch 5] PLAT    | Starting to set up Airtouch5 platform.
[6/11/2025, 10:11:20 AM] Loading 3 accessories...
[6/11/2025, 10:11:20 AM] [Airtouch 5] PLAT    | Executed didFinishLaunching callback
[6/11/2025, 10:11:20 AM] [Airtouch 5] PLAT    | Defined units in config, not doing automated discovery
[6/11/2025, 10:11:20 AM] [Airtouch 5] API     | Connected to Airtouch: 192.168.86.142
[6/11/2025, 10:11:20 AM] [Airtouch 5] ATWRAP  | Creating AC Kids (0)
[6/11/2025, 10:11:20 AM] [Airtouch 5] ATWRAP  | AC Configuration:  Name: Kids,   Zones: 4 (starting from 0),   Modes: Auto, Cool, Heat, Dry, Fan,   Fan Speeds: Auto, Low, Medium, High,   Cool Range: 20°C - 32°C,   Heat Range: 16°C - 32°C
[6/11/2025, 10:11:20 AM] [Airtouch 5] ATWRAP  | Kids details: Off | Heat | 17.0°C → 22.0°C
[6/11/2025, 10:11:20 AM] [Airtouch 5] ATWRAP  | Register AC being called for acnumber: 0
[6/11/2025, 10:11:20 AM] TypeError: Cannot read properties of undefined (reading 'ac_ability')
    at Airtouch5Wrapper.AddUpdateAcStatus (/volume1/homebridge/node_modules/homebridge-airtouch5-platform/src/airTouchWrapper.ts:222:41)
    at AirtouchPlatform.onACStatusNotification (/volume1/homebridge/node_modules/homebridge-airtouch5-platform/src/platform.ts:239:14)
    at EventEmitter.<anonymous> (/volume1/homebridge/node_modules/homebridge-airtouch5-platform/src/platform.ts:126:12)
    at EventEmitter.emit (node:events:524:28)
    at AirtouchAPI.decode_ac_status (/volume1/homebridge/node_modules/homebridge-airtouch5-platform/src/api.ts:873:20)
    at AirtouchAPI.decode_standard_message (/volume1/homebridge/node_modules/homebridge-airtouch5-platform/src/api.ts:519:12)
    at Socket.<anonymous> (/volume1/homebridge/node_modules/homebridge-airtouch5-platform/src/api.ts:1147:14)
    at Socket.emit (node:events:524:28)
    at addChunk (node:internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
[6/11/2025, 10:11:20 AM] Got SIGTERM, shutting down Homebridge...
[6/11/2025, 10:11:20 AM] [Airtouch 5] ATWRAP  | Zone Details: Name: Zone 0, Power: Off, Control: Temperature, Current: 16.4°C, Target: 22.0°C, Damper: 40%, Sensor: Yes
[6/11/2025, 10:11:20 AM] [Airtouch 5] ATWRAP  | Zone Details: Name: Zone 1, Power: Off, Control: Temperature, Current: 18.2°C, Target: 22.0°C, Damper: 10%, Sensor: Yes
[6/11/2025, 10:11:20 AM] [Airtouch 5] ATWRAP  | Zone Details: Name: Zone 2, Power: Off, Control: Temperature, Current: 18.2°C, Target: 22.0°C, Damper: 60%, Sensor: Yes
[6/11/2025, 10:11:20 AM] [Airtouch 5] ATWRAP  | Zone Details: Name: Zone 3, Power: Off, Control: Temperature, Current: 18.2°C, Target: 22.0°C, Damper: 100%, Sensor: Yes
[6/11/2025, 10:11:20 AM] TypeError: Cannot read properties of undefined (reading 'zone_name')
    at Airtouch5Wrapper.AddUpdateZoneStatus (/volume1/homebridge/node_modules/homebridge-airtouch5-platform/src/airTouchWrapper.ts:156:53)
    at AirtouchPlatform.onZoneStatusNotification (/volume1/homebridge/node_modules/homebridge-airtouch5-platform/src/platform.ts:252:14)
    at EventEmitter.<anonymous> (/volume1/homebridge/node_modules/homebridge-airtouch5-platform/src/platform.ts:134:12)
    at EventEmitter.emit (node:events:524:28)
    at AirtouchAPI.decode_zones_status (/volume1/homebridge/node_modules/homebridge-airtouch5-platform/src/api.ts:921:20)
    at AirtouchAPI.decode_standard_message (/volume1/homebridge/node_modules/homebridge-airtouch5-platform/src/api.ts:517:12)
    at Socket.<anonymous> (/volume1/homebridge/node_modules/homebridge-airtouch5-platform/src/api.ts:1147:14)
    at Socket.emit (node:events:524:28)
    at addChunk (node:internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
[6/11/2025, 10:11:20 AM] Got SIGTERM, shutting down child bridge process...

**Comment by cemilbrowne** [comment]
@captaincafeman just pushed a version that may fix it.  If nothing else, it should give us more debugging.  Can you update to 2.0.1 and test? Look for a line like this:

[6/11/2025, 2:21:19 PM] [Airtouch 5] API     | Got an AC Ability message, overall length 26, number of ACs in message 1

**Comment by captaincafeman** [comment]
Updated logs - repeats because it crashes with a sigterm after the error. Looks like it's finding the slave system though so good progress!

-----

[6/11/2025, 7:01:20 PM] [Airtouch 5] Initializing Airtouch5 platform...
[6/11/2025, 7:01:20 PM] [Airtouch 5] PLAT    | Starting to set up Airtouch5 platform.
[6/11/2025, 7:01:20 PM] [Airtouch 5] PLAT    | Executed didFinishLaunching callback
[6/11/2025, 7:01:20 PM] [Airtouch 5] PLAT    | Defined units in config, not doing automated discovery
[6/11/2025, 7:01:20 PM] [Airtouch 5] API     | Connected to Airtouch: 192.168.86.142
[6/11/2025, 7:01:20 PM] [Airtouch 5] API     | Got an AC Ability message, overall length 52, number of ACs in message 2
[6/11/2025, 7:01:20 PM] [Airtouch 5] ATWRAP  | Creating AC Kids (0)
[6/11/2025, 7:01:20 PM] [Airtouch 5] ATWRAP  | AC Configuration:  Name: Kids,   Zones: 4 (starting from 0),   Modes: Auto, Cool, Heat, Dry, Fan,   Fan Speeds: Auto, Low, Medium, High,   Cool Range: 20°C - 32°C,   Heat Range: 16°C - 32°C
[6/11/2025, 7:01:20 PM] [Airtouch 5] ATWRAP  | Creating AC Parents (1)
[6/11/2025, 7:01:20 PM] [Airtouch 5] ATWRAP  | AC Configuration:  Name: Parents,   Zones: 3 (starting from 4),   Modes: Auto, Cool, Heat, Dry, Fan,   Fan Speeds: Auto, Low, Medium, High,   Cool Range: 20°C - 32°C,   Heat Range: 16°C - 32°C
[6/11/2025, 7:01:20 PM] [Airtouch 5] ATWRAP  | Kids details: Off | Heat | 20.0°C → 22.0°C
[6/11/2025, 7:01:20 PM] [Airtouch 5] ATWRAP  | Register AC being called for acnumber: 0
[6/11/2025, 7:01:20 PM] TypeError: Cannot read properties of undefined (reading 'ac_ability')
    at Airtouch5Wrapper.AddUpdateAcStatus (/volume1/homebridge/node_modules/homebridge-airtouch5-platform/src/airTouchWrapper.ts:222:41)
    at AirtouchPlatform.onACStatusNotification (/volume1/homebridge/node_modules/homebridge-airtouch5-platform/src/platform.ts:239:14)
    at EventEmitter.<anonymous> (/volume1/homebridge/node_modules/homebridge-airtouch5-platform/src/platform.ts:126:12)
    at EventEmitter.emit (node:events:524:28)
    at AirtouchAPI.decode_ac_status (/volume1/homebridge/node_modules/homebridge-airtouch5-platform/src/api.ts:873:20)
    at AirtouchAPI.decode_standard_message (/volume1/homebridge/node_modules/homebridge-airtouch5-platform/src/api.ts:519:12)
    at Socket.<anonymous> (/volume1/homebridge/node_modules/homebridge-airtouch5-platform/src/api.ts:1147:14)
    at Socket.emit (node:events:524:28)
    at addChunk (node:internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
[6/11/2025, 7:01:20 PM] Got SIGTERM, shutting down Homebridge...
[6/11/2025, 7:01:20 PM] [Airtouch 5] ATWRAP  | Zone Details: Name: Zone 0, Power: Off, Control: Temperature, Current: 20.4°C, Target: 22.0°C, Damper: 100%, Sensor: Yes
[6/11/2025, 7:01:20 PM] [Airtouch 5] ATWRAP  | Zone Details: Name: Zone 1, Power: Off, Control: Temperature, Current: 21.3°C, Target: 22.0°C, Damper: 0%, Sensor: Yes
[6/11/2025, 7:01:20 PM] [Airtouch 5] ATWRAP  | Zone Details: Name: Zone 2, Power: Off, Control: Temperature, Current: 22.7°C, Target: 22.0°C, Damper: 0%, Sensor: Yes
[6/11/2025, 7:01:20 PM] [Airtouch 5] ATWRAP  | Zone Details: Name: Zone 3, Power: Off, Control: Temperature, Current: 20.5°C, Target: 22.0°C, Damper: 100%, Sensor: Yes
[6/11/2025, 7:01:20 PM] [Airtouch 5] ATWRAP  | Zone Details: Name: Zone 4, Power: Off, Control: Temperature, Current: 21.0°C, Target: 22.0°C, Damper: 65%, Sensor: Yes
[6/11/2025, 7:01:20 PM] [Airtouch 5] ATWRAP  | Zone Details: Name: Zone 5, Power: Off, Control: Temperature, Current: 20.3°C, Target: 22.0°C, Damper: 100%, Sensor: Yes
[6/11/2025, 7:01:20 PM] [Airtouch 5] ATWRAP  | Zone Details: Name: Zone 6, Power: Off, Control: Temperature, Current: 20.7°C, Target: 22.0°C, Damper: 80%, Sensor: Yes
[6/11/2025, 7:01:33 PM] [Airtouch 5] Initializing Airtouch5 platform...
[6/11/2025, 7:01:33 PM] [Airtouch 5] PLAT    | Starting to set up Airtouch5 platform.
[6/11/2025, 7:01:33 PM] [Airtouch 5] PLAT    | Executed didFinishLaunching callback
[6/11/2025, 7:01:33 PM] [Airtouch 5] PLAT    | Defined units in config, not doing automated discovery
[6/11/2025, 7:01:33 PM] [Airtouch 5] API     | Connected to Airtouch: 192.168.86.142
[6/11/2025, 7:01:33 PM] [Airtouch 5] API     | Got an AC Ability message, overall length 52, number of ACs in message 2
[6/11/2025, 7:01:33 PM] [Airtouch 5] ATWRAP  | Creating AC Kids (0)
[6/11/2025, 7:01:33 PM] [Airtouch 5] ATWRAP  | AC Configuration:  Name: Kids,   Zones: 4 (starting from 0),   Modes: Auto, Cool, Heat, Dry, Fan,   Fan Speeds: Auto, Low, Medium, High,   Cool Range: 20°C - 32°C,   Heat Range: 16°C - 32°C
[6/11/2025, 7:01:33 PM] [Airtouch 5] ATWRAP  | Creating AC Parents (1)
[6/11/2025, 7:01:33 PM] [Airtouch 5] ATWRAP  | AC Configuration:  Name: Parents,   Zones: 3 (starting from 4),   Modes: Auto, Cool, Heat, Dry, Fan,   Fan Speeds: Auto, Low, Medium, High,   Cool Range: 20°C - 32°C,   Heat Range: 16°C - 32°C
[6/11/2025, 7:01:33 PM] [Airtouch 5] ATWRAP  | Kids details: Off | Heat | 20.0°C → 22.0°C
[6/11/2025, 7:01:33 PM] [Airtouch 5] ATWRAP  | Register AC being called for acnumber: 0
[6/11/2025, 7:01:33 PM] TypeError: Cannot read properties of undefined (reading 'ac_ability')
    at Airtouch5Wrapper.AddUpdateAcStatus (/volume1/homebridge/node_modules/homebridge-airtouch5-platform/src/airTouchWrapper.ts:222:41)
    at AirtouchPlatform.onACStatusNotification (/volume1/homebridge/node_modules/homebridge-airtouch5-platform/src/platform.ts:239:14)
    at EventEmitter.<anonymous> (/volume1/homebridge/node_modules/homebridge-airtouch5-platform/src/platform.ts:126:12)
    at EventEmitter.emit (node:events:524:28)
    at AirtouchAPI.decode_ac_status (/volume1/homebridge/node_modules/homebridge-airtouch5-platform/src/api.ts:873:20)
    at AirtouchAPI.decode_standard_message (/volume1/homebridge/node_modules/homebridge-airtouch5-platform/src/api.ts:519:12)
    at Socket.<anonymous> (/volume1/homebridge/node_modules/homebridge-airtouch5-platform/src/api.ts:1147:14)
    at Socket.emit (node:events:524:28)
    at addChunk (node:internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)

**Comment by cemilbrowne** [comment]
I've fixed nothing, but added a little debugging - can you try this please? Prerelease, so you might have to specifically download that version. 

homebridge-airtouch5-platform@2.0.2-0

**Comment by captaincafeman** [comment]
I'm getting an invalid version error when I try to install it - detailed logs below:

------------

0 verbose cli /volume1/@appstore/Node.js_v22/usr/local/bin/node /var/packages/homebridge/target/app/bin/npm
1 info using npm@10.9.2
2 info using node@v22.13.1
3 silly config load:file:/volume1/@appstore/homebridge/app/lib/node_modules/npm/npmrc
4 warn config global-style This option has been deprecated in favor of `--install-strategy=shallow`
5 silly config load:file:/volume1/homebridge/.npmrc
6 warn config global-style This option has been deprecated in favor of `--install-strategy=shallow`
7 silly config load:file:/var/packages/homebridge/home/.npmrc
8 silly config load:file:/var/packages/homebridge/target/app/etc/npmrc
9 verbose title npm install homebridge-airtouch5-platform@2.0.2-0
10 verbose argv "install" "--save" "--omit" "dev" "homebridge-airtouch5-platform@2.0.2-0"
11 verbose logfile logs-max:10 dir:/var/packages/homebridge/home/.npm/_logs/2025-06-12T00_00_09_475Z-
12 verbose logfile /var/packages/homebridge/home/.npm/_logs/2025-06-12T00_00_09_475Z-debug-0.log
13 silly logfile start cleaning logs, removing 2 files
14 silly packumentCache heap:2197815296 maxSize:549453824 maxEntrySize:274726912
15 silly logfile done cleaning log files
16 silly idealTree buildDeps
17 silly fetch manifest homebridge-airtouch5-platform@2.0.2-0
18 silly packumentCache full:https://registry.npmjs.org/homebridge-airtouch5-platform cache-miss
19 http fetch GET 200 https://registry.npmjs.org/homebridge-airtouch5-platform 227ms (cache miss)
20 silly packumentCache full:https://registry.npmjs.org/homebridge-airtouch5-platform set size:undefined disposed:false
21 silly placeDep ROOT homebridge-airtouch5-platform@2.0.2-0 REPLACE for:  want: 2.0.2-0
22 silly fetch manifest debug@^4.1.1
23 silly packumentCache full:https://registry.npmjs.org/debug cache-miss
24 http fetch GET 200 https://registry.npmjs.org/debug 52ms (cache miss)
25 silly packumentCache full:https://registry.npmjs.org/debug set size:undefined disposed:false
26 silly placeDep node_modules/homebridge-camera-ui debug@4.4.1 KEEP for: mqtt@4.2.8 want: ^4.1.1
27 verbose stack TypeError: Invalid Version: 
27 verbose stack     at new SemVer (/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/semver/classes/semver.js:38:13)
27 verbose stack     at compare (/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/semver/functions/compare.js:3:32)
27 verbose stack     at Object.gte (/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/semver/functions/gte.js:2:30)
27 verbose stack     at Node.canDedupe (/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/node.js:1081:32)
27 verbose stack     at PlaceDep.pruneDedupable (/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/place-dep.js:426:14)
27 verbose stack     at PlaceDep.pruneDedupable (/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/place-dep.js:444:14)
27 verbose stack     at PlaceDep.pruneDedupable (/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/place-dep.js:444:14)
27 verbose stack     at new PlaceDep (/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/place-dep.js:219:12)
27 verbose stack     at #buildDepStep (/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:920:18)
27 verbose stack     at async Arborist.buildIdealTree (/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:181:7)
28 error Invalid Version: 
29 silly unfinished npm timer reify 1749686409761
30 silly unfinished npm timer reify:loadTrees 1749686409762
31 silly unfinished npm timer idealTree:buildDeps 1749686410541
32 silly unfinished npm timer idealTree:node_modules/homebridge-camera-ui/node_modules/mqtt 1749686410780
33 verbose cwd /volume1/homebridge
34 verbose os Linux 4.4.302+
35 verbose node v22.13.1
36 verbose npm  v10.9.2
37 verbose exit 1
38 verbose code 1
39 error A complete log of this run can be found in: /var/packages/homebridge/home/.npm/_logs/2025-06-12T00_00_09_475Z-debug-0.log

**Comment by cemilbrowne** [comment]
Odd.  Can you try again and grab 2.0.2 @captaincafeman ?

**Comment by captaincafeman** [comment]
OK, now we're cooking! The bug was on my side - Homebridge had corrupted itself somehow with the latest upgrade and could no longer see the latest version of npm. Have re-installed with a clean installation and almost everything is working, all systems have been found and added correctly with v2.0.02 and the plug-in is operating as expected. Thanks for this!

Only one bug remaining, the "master" control of the slave unit isn't working - [see linked photos](https://imgur.com/a/jEJO1Qe):

**Comment by cemilbrowne** [comment]
is the issue that it's not controlling the slave unit in reality, or that it's not reflecting in HomeKit? @captaincafeman

**Comment by captaincafeman** [comment]
It's not saving state for temperature change on the slave unit - updates in Home show up briefly in the Home UI, are replicated on the Air Touch unit, but then almost instantly reverted back to whatever settings were on the Air Touch before. For example:

### On / Off state changes

**Starting state: Slave Unit off** 
- Home UI displays Slave Unit off (correct) with ambient temperature of 0 degrees (incorrect)
- Air Touch displays Slave Unit off (correct) with ambient temperature of 22 degrees (correct)

**Turn Slave Unit On using Air Touch (existing setting is Heat-22)**
- Home UI displays Slave Unit off (incorrect) with ambient temperature of 0 degrees (incorrect)
- Air Touch displays Slave Unit on at Heat-22 (correct) with ambient of 22 degrees (correct)

**Turn Slave Unit Off using Air Touch**
- Home UI displays Slave Unit off (incorrect) with ambient temperature of 0 degrees (incorrect)
- Air Touch displays Slave Unit off (correct) with ambient temperature of 22 degrees (correct)

**Turn Slave Unit On using Home App, (existing setting is Heat-22)**
- Home UI displays Slave Unit on (correct) with ambient temperature of 0 degrees (incorrect) at Auto / Keep between 15-15 (incorrect)
- Air Touch displays Slave Unit on (correct) at Heat-22 (correct) with ambient of 22 degrees (correct)

**Turn Slave Unit Off using Home App**
- Home UI displays Slave Unit off (correct) with ambient temperature of 0 degrees (incorrect)
- Air Touch displays Slave Unit off (correct) with ambient temperature of 22 degrees (correct)

### Temperature state changes (with both Home App and Air Touch showing Slave Unit as On)

**Set Temperature on Slave Unit to Heat-23 using Air Touch**
- Home UI displays Slave Unit on (correct) with ambient temperature of 0 degrees (incorrect) at Auto / Keep between 15-15 (incorrect)
- Air Touch displays Slave Unit on (correct) at Heat-23 (correct)
 
**Set Temperature on Slave Unit to Heat-23 using Home App** 
- Home UI displays Slave Unit on (correct) at Heat-23 (correct) while in the temperature adjustment view but on exit the main UI shows the Slave Unit as off (incorrect)  with ambient temperature of 0 degrees (incorrect) at Auto / Keep between 15-15 (incorrect)
- Air Touch briefly updates Slave Unit to Heat-23 (correct) but then almost immediately defaults back to prior settings of Heat-22 (incorrect)

**Comment by cemilbrowne** [comment]
sorry @captaincafeman ; I lose you there - could you augment the list with which unit is not updating correctly [master/slave] and potentially add some debug logging for me when you try it?  I suspect I know what's going on, but it'll help me chase it.

**Comment by captaincafeman** [comment]
I've edited to hopefully make it clearer. I'm not sure how to generate logs as it seems to be primarily related to state changes not being sent to or received from Homebridge correctly from the Home App UI. Happy to do whatever's needed though

**Comment by captaincafeman** [comment]
Also, just to be totally clear, every individual zone is displaying correct data and responding as expected. It's only the "global" unit control setting for the Slave Unit that's behaving incorrectly and showing incorrect data. I'm not sure what the official term for it is, on my Air Touch it's the controls on the right-hand side that turn the entire unit on / off. The Master Unit is behaving as expected from the Home App, it's only the Slave Unit that isn't behaving as expected.

**Comment by captaincafeman** [comment]
Also, just to be totally clear, every individual zone is displaying correct data and responding as expected. It's only the "global" unit control setting for the Slave Unit that's behaving incorrectly and showing incorrect data. I'm not sure what the official term for it is, on my Air Touch it's the controls on the right-hand side that turn the entire unit on / off. The Master Unit is behaving as expected from the Home App, it's only the Slave Unit that isn't behaving as expected.

**Comment by cemilbrowne** [comment]
Cool!  That narrows it down.  Let me see what I can do.  I don't generally adjust the 'AC' unit much, in fact I hide it on my homekit screen, and do everything through the zones.  I'll double check!

**Comment by captaincafeman** [comment]
Honestly, I don't use it either - I just wanted to let you know in case someone else wants to use it in the future!

**Comment by cemilbrowne** [comment]
The debug logs in there would still help me to know whether status is being done right.... @captaincafeman

**Comment by captaincafeman** [comment]
Will do, unfortunately I'm about to head overseas for a few weeks - will update when I get back if someone else doesn't do it first.
